// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("0.1.1")]
[assembly: AssemblyFileVersion("0.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "0.1.1";
        internal const System.String AssemblyFileVersion = "0.1.1";
    }
}
